DEFAULT_BRANCH: main
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - DOCKERFILE_DOCKERFILELINT
  - SPELL_CSPELL
  - DOCKERFILE_HADOLINT
EXCLUDED_DIRECTORIES: [.git, bin, obj]
FILTER_REGEX_EXCLUDE: (.*CHANGELOG.md)
LOG_LEVEL: WARNING
